// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BackendProyectoTienda.Models;

public partial class Articulo
{
    public int Id { get; set; }

    public string Codigo { get; set; }

    public string Nombre { get; set; }

    public string Descripcion { get; set; }

    public decimal Precio { get; set; }

    public int Stock { get; set; }

    public decimal Iva { get; set; }

    public int? SubfamiliaId { get; set; }

    public virtual ICollection<DetallesFactura> DetallesFacturas { get; set; } = new List<DetallesFactura>();

    public virtual Subfamilia Subfamilia { get; set; }
}