// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BackendProyectoTienda.Models;

public partial class DetallesFactura
{
    public int FacturaId { get; set; }

    public int ArticuloId { get; set; }

    public int Cantidad { get; set; }

    public decimal PrecioUnitario { get; set; }

    public decimal Iva { get; set; }

    public virtual Articulo Articulo { get; set; }

    public virtual Factura Factura { get; set; }
}