// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BackendProyectoTienda.Models;

public partial class Empresa
{
    public int Id { get; set; }

    public string Nombre { get; set; }

    public string Direccion { get; set; }

    public string Telefono { get; set; }

    public string Email { get; set; }

    public string Nif { get; set; }

    public virtual ICollection<Factura> Facturas { get; set; } = new List<Factura>();
}