// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BackendProyectoTienda.Models;

public partial class Familia
{
    public int Id { get; set; }

    public string Nombre { get; set; }

    public virtual ICollection<Subfamilia> Subfamilia { get; set; } = new List<Subfamilia>();
}