// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BackendProyectoTienda.Models;

public partial class Subfamilia
{
    public int Id { get; set; }

    public string Nombre { get; set; }

    public int? FamiliaId { get; set; }

    public virtual ICollection<Articulo> Articulos { get; set; } = new List<Articulo>();

    public virtual Familia Familia { get; set; }
}